from setuptools import setup
import os
from glob import glob

package_name = 'xpi_sensors'

setup(
    name=package_name,
    version='0.1.0',
    packages=[package_name],
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        (os.path.join('share', package_name, 'launch'), glob('launch/*.launch.py')),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='XPI Maintainer',
    maintainer_email='user@example.com',
    description='Sensor blocks for XPI',
    license='MIT',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'ads1115_node = xpi_sensors.ads1115_node:main',
            'aht20_node = xpi_sensors.aht20_node:main',
            'analog_mux_4067_node = xpi_sensors.analog_mux_4067_node:main',
            'analog_sensor_interpreter_node = xpi_sensors.analog_sensor_interpreter_node:main',
            'anemometer_node = xpi_sensors.anemometer_node:main',
            'apds9960_node = xpi_sensors.apds9960_node:main',
            'as7341_node = xpi_sensors.as7341_node:main',
            'audio_level_node = xpi_sensors.audio_level_node:main',
            'bh1750_node = xpi_sensors.bh1750_node:main',
            'bme280_node = xpi_sensors.bme280_node:main',
            'bme680_node = xpi_sensors.bme680_node:main',
            'bmp085_node = xpi_sensors.bmp085_node:main',
            'bno055_node = xpi_sensors.bno055_node:main',
            'ccs811_node = xpi_sensors.ccs811_node:main',
            'dht_node = xpi_sensors.dht_node:main',
            'ds18b20_node = xpi_sensors.ds18b20_node:main',
            'gpio_digital_input_node = xpi_sensors.gpio_digital_input_node:main',
            'gps_node = xpi_sensors.gps_node:main',
            'hx711_node = xpi_sensors.hx711_node:main',
            'ina219_node = xpi_sensors.ina219_node:main',
            'lm75a_node = xpi_sensors.lm75a_node:main',
            'max17048_node = xpi_sensors.max17048_node:main',
            'max44009_node = xpi_sensors.max44009_node:main',
            'mpu6050_node = xpi_sensors.mpu6050_node:main',
            'mpu9250_node = xpi_sensors.mpu9250_node:main',
            'nfc_reader_node = xpi_sensors.nfc_reader_node:main',
            'opt3001_node = xpi_sensors.opt3001_node:main',
            'pir_node = xpi_sensors.pir_node:main',
            'pms5003_node = xpi_sensors.pms5003_node:main',
            'qmc5883l_node = xpi_sensors.qmc5883l_node:main',
            'rain_gauge_node = xpi_sensors.rain_gauge_node:main',
            'respeaker_node = xpi_sensors.respeaker_node:main',
            'scd4x_node = xpi_sensors.scd4x_node:main',
            'sgp30_node = xpi_sensors.sgp30_node:main',
            'shift_register_165_node = xpi_sensors.shift_register_165_node:main',
            'sht3x_node = xpi_sensors.sht3x_node:main',
            'sonar_node = xpi_sensors.sonar_node:main',
            'tcs3200_node = xpi_sensors.tcs3200_node:main',
            'tcs34725_node = xpi_sensors.tcs34725_node:main',
            'tf_lidar_node = xpi_sensors.tf_serial_node:main',
            'tfmini_plus_node = xpi_sensors.tfmini_plus_node:main',
            'tsl2561_node = xpi_sensors.tsl2561_node:main',
            'tsl2591_node = xpi_sensors.tsl2591_node:main',
            'veml6070_node = xpi_sensors.veml6070_node:main',
            'vl53l1x_node = xpi_sensors.vl53l1x_node:main',
            'wind_vane_digital_node = xpi_sensors.wind_vane_digital_node:main',
            'wind_vane_node = xpi_sensors.wind_vane_node:main',
            'yamnet_node = xpi_sensors.yamnet_node:main',
        ],
    },
)